import {createHash,randomBytes,randomUUID,scrypt,timingSafeEqual} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {z} from 'zod';
import {DomainError} from './service.ts';
import type {Principal} from '../../contracts/src/index.ts';
export const tokenHash=(s:string)=>createHash('sha256').update(s).digest('hex');
const token=()=>randomBytes(32).toString('base64url');
const fail=(code:string,message:string,status=400):never=>{throw new DomainError(code,message,status);};
const username=z.string().regex(/^[A-Za-z0-9._-]{3,40}$/).transform(s=>s.toLowerCase());
const password=z.string().min(15).max(128);
const name=z.string().trim().min(1).max(100);
const parse=<T>(schema:z.ZodType<T>,body:unknown):T=>{const r=schema.safeParse(body);return r.success?r.data:fail('VALIDATION','Invalid request',400);};
let hashing=0;
export async function passwordHash(value:string,salt=randomBytes(16).toString('hex')) {if(hashing>=2) fail('RATE_LIMITED','Try again later',429);hashing++;try {const key=await new Promise<Buffer>((resolve,reject)=>scrypt(value,salt,64,{N:131072,r:8,p:1,maxmem:160*1024*1024},(e,k)=>e?reject(e):resolve(k)));return `${salt}:${key.toString('hex')}`;}finally{hashing--;}}
export class CloudAuth {
 constructor(private pool:Pool){}
 private async tx<T>(fn:(c:PoolClient)=>Promise<T>){const c=await this.pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(77321)');const r=await fn(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 private async human(c:PoolClient,p:Principal,owner=false){const u=(await c.query('SELECT u.* FROM graybox.users u JOIN graybox.credentials c ON c.human_id=u.id WHERE c.id=$1 AND c.kind=\'human\' AND c.revoked_at IS NULL AND c.expires_at>clock_timestamp() AND u.disabled_at IS NULL FOR SHARE OF u,c',[p.id])).rows[0];if(!u)fail('UNAUTHORIZED','Human session required',401);if(owner&&u.role!=='owner')fail('FORBIDDEN','Owner required',403);return u;}
 private async issue(c:PoolClient,u:{id:string;name:string;role:string},agent?:string,projects:string[]|null=null){const raw=token(),expires=agent?new Date(Date.now()+90*86400000).toISOString():'9999-12-31T23:59:59.000Z';await c.query('INSERT INTO graybox.credentials(id,human_id,agent_id,kind,token_hash,label,project_ids,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[randomUUID(),u.id,agent??null,agent?'agent':'human',tokenHash(raw),randomUUID(),projects===null?null:JSON.stringify(projects),expires]);const environment=(await c.query("SELECT value FROM graybox.metadata WHERE key='environment_id'")).rows[0].value;const workspace=(await c.query('SELECT id FROM graybox.workspaces ORDER BY id LIMIT 1')).rows[0]?.id;if(!workspace)fail('UNAVAILABLE','Workspace not initialized',503);return {token:raw,expires_at:expires,profile:{id:u.id,name:u.name,role:u.role},environment_id:environment,workspace_id:workspace};}
 async login(body:unknown){const b=parse(z.object({username,password}).strict(),body);const u=(await this.pool.query('SELECT * FROM graybox.users WHERE username=$1',[b.username])).rows[0];const encoded=u?.password_hash??'00000000000000000000000000000000:'+('0'.repeat(128));const candidate=await passwordHash(b.password,encoded.split(':')[0]);if(!timingSafeEqual(Buffer.from(candidate),Buffer.from(encoded)))fail('UNAUTHORIZED','Incorrect username or password',401);return this.tx(async c=>{const current=(await c.query('SELECT * FROM graybox.users WHERE id=$1 AND disabled_at IS NULL FOR SHARE',[u.id])).rows[0];if(!current)fail('UNAUTHORIZED','Incorrect username or password',401);return this.issue(c,current);});}
 async redeem(body:unknown){const b=parse(z.object({code:z.string().min(40).max(200),username,password,name}).strict(),body);const encoded=await passwordHash(b.password);return this.tx(async c=>{const invite=(await c.query('SELECT * FROM graybox.invitations WHERE code_hash=$1 AND used_at IS NULL AND expires_at>clock_timestamp() FOR UPDATE',[tokenHash(b.code)])).rows[0];if(!invite)fail('INVALID_CODE','Invitation unavailable',409);const count=(await c.query('SELECT count(*)::int n FROM graybox.users WHERE disabled_at IS NULL')).rows[0].n;if(count>=3)fail('MEMBER_LIMIT','Team is full',409);if((await c.query('SELECT 1 FROM graybox.users WHERE username=$1 OR ($2=\'owner\' AND role=\'owner\')',[b.username,invite.role])).rowCount)fail('CONFLICT','Account unavailable',409);const u={id:randomUUID(),name:b.name,role:invite.role};await c.query('INSERT INTO graybox.users(id,name,role,username,password_hash) VALUES($1,$2,$3,$4,$5)',[u.id,u.name,u.role,b.username,encoded]);await c.query('UPDATE graybox.invitations SET used_at=now() WHERE code_hash=$1',[tokenHash(b.code)]);return this.issue(c,u);});}
 async pairStart(body:unknown){const b=parse(z.object({name}).strict(),body);return this.tx(async c=>{if((await c.query('SELECT count(*)::int n FROM graybox.pairs WHERE expires_at>clock_timestamp() AND consumed_at IS NULL')).rows[0].n>=20)fail('RATE_LIMITED','Too many pending pairs',429);const device=token(),user=token(),expires=new Date(Date.now()+600000).toISOString();await c.query('INSERT INTO graybox.pairs(device_hash,user_hash,name,expires_at) VALUES($1,$2,$3,$4)',[tokenHash(device),tokenHash(user),b.name,expires]);return {device_code:device,user_code:user,expires_at:expires};});}
 async pairPoll(body:unknown){const b=parse(z.object({device_code:z.string().min(40).max(200)}).strict(),body);return this.tx(async c=>{const pair=(await c.query('SELECT * FROM graybox.pairs WHERE device_hash=$1 AND expires_at>clock_timestamp() AND consumed_at IS NULL FOR UPDATE',[tokenHash(b.device_code)])).rows[0];if(!pair)fail('INVALID_CODE','Pair unavailable',409);if(!pair.human_id)return {status:'pending' as const};const u=(await c.query('SELECT * FROM graybox.users WHERE id=$1 AND disabled_at IS NULL FOR SHARE',[pair.human_id])).rows[0];if(!u)fail('INVALID_CODE','Pair unavailable',409);const id=randomUUID();await c.query('INSERT INTO graybox.agents(id,human_id,name) VALUES($1,$2,$3)',[id,u.id,pair.name]);const issued=await this.issue(c,u,id,pair.project_ids);await c.query('UPDATE graybox.pairs SET consumed_at=now() WHERE device_hash=$1',[pair.device_hash]);const {profile,...result}=issued;return {status:'approved' as const,...result,agent_id:id,human_id:u.id};});}
 async action(p:Principal,path:string,body:unknown,id?:string){return this.tx(async c=>{const u=await this.human(c,p,path==='invite'||path==='disable');if(path==='me'){const r=(await c.query('SELECT expires_at FROM graybox.credentials WHERE id=$1',[p.id])).rows[0];return {profile:{id:u.id,name:u.name,role:u.role},expires_at:r.expires_at};}if(path==='members')return (await c.query('SELECT id,name,role,disabled_at,avatar_data FROM graybox.users ORDER BY role,name')).rows;if(path==='agents')return (await c.query('SELECT a.id,a.human_id,a.name,c.revoked_at,c.project_ids,c.expires_at FROM graybox.agents a JOIN graybox.credentials c ON c.agent_id=a.id WHERE ($1=\'owner\' OR a.human_id=$2) ORDER BY a.name',[u.role,u.id])).rows;
 if(path==='approve'){const b=parse(z.object({user_code:z.string().min(40).max(200),project_ids:z.array(z.uuid()).max(100).nullable()}).strict(),body);if(b.project_ids){const rows=(await c.query('SELECT id FROM graybox.projects WHERE id=ANY($1::uuid[]) AND deleted_at IS NULL',[b.project_ids])).rows;if(rows.length!==new Set(b.project_ids).size)fail('VALIDATION','Unknown project',400);}const r=await c.query('UPDATE graybox.pairs SET human_id=$2,project_ids=$3 WHERE user_hash=$1 AND expires_at>clock_timestamp() AND consumed_at IS NULL AND human_id IS NULL',[tokenHash(b.user_code),u.id,b.project_ids===null?null:JSON.stringify(b.project_ids)]);if(!r.rowCount)fail('INVALID_CODE','Pair unavailable',409);return {ok:true};}
 parse(z.object({}).strict(),body);if(path==='invite'){const raw=token(),expires=new Date(Date.now()+86400000).toISOString();await c.query('INSERT INTO graybox.invitations(code_hash,role,expires_at) VALUES($1,\'member\',$2)',[tokenHash(raw),expires]);return {code:raw,expires_at:expires};}if(path==='logout')await c.query('UPDATE graybox.credentials SET revoked_at=now() WHERE id=$1',[p.id]);else if(path==='disable'){const r=await c.query('UPDATE graybox.users SET disabled_at=now() WHERE id=$1 AND role<>\'owner\' RETURNING id',[id]);if(!r.rowCount)fail('FORBIDDEN','Cannot disable this member',403);await c.query('UPDATE graybox.credentials SET revoked_at=now() WHERE human_id=$1',[id]);}else if(path==='revoke'){const r=await c.query('UPDATE graybox.credentials SET revoked_at=now() WHERE agent_id=$1 AND ($2=\'owner\' OR human_id=$3)',[id,u.role,u.id]);if(!r.rowCount)fail('NOT_FOUND','Agent unavailable',404);}return {ok:true};});}
}
