import {beforeAll,afterAll,beforeEach,test,expect} from 'vitest';
import {Pool} from 'pg';
import {config} from 'dotenv';
import {readFile} from 'node:fs/promises';
import {buildApp} from '../../apps/api/src/app.ts';
import {migrate} from '../../packages/db/src/migrate.ts';
config({quiet:true});
const url=process.env.GRAYBOX_TEST_ADMIN_URL!;
if(new URL(url).pathname!=='/graybox_test') throw Error('Isolated test DB required');
const pool=new Pool({connectionString:url});
let app:Awaited<ReturnType<typeof buildApp>>;
beforeEach(async()=>{await adminReset();app=await buildApp({pool,authPool:pool,mode:'cloud'});});
async function adminReset(){await app?.close();await pool.query('DROP SCHEMA IF EXISTS graybox CASCADE');await migrate(pool);await pool.query(await readFile(new URL('../../db/migrations/002_cloud_auth.sql',import.meta.url),'utf8'));}
afterAll(async()=>{await app?.close();await pool.end();});
test('cloud rejects seeded local credential and public registration',async()=>{expect((await app.inject({method:'GET',url:'/v1/me',headers:{authorization:'Bearer local-owner'}})).statusCode).toBe(401);expect((await app.inject({method:'POST',url:'/v1/auth/register',payload:{}})).statusCode).toBe(401);});
test('pairing has independent codes and one pending result',async()=>{const start=await app.inject({method:'POST',url:'/v1/auth/pair/start',payload:{name:'Agent'}});expect(start.statusCode).toBe(200);const pair=start.json().data;expect(pair.device_code).not.toBe(pair.user_code);expect(pair.device_code.length).toBeGreaterThanOrEqual(43);const poll=await app.inject({method:'POST',url:'/v1/auth/pair/poll',payload:{device_code:pair.device_code}});expect(poll.json().data).toEqual({status:'pending'});});
import {bootstrapCloud} from '../../scripts/cloud-bootstrap.ts';
async function call(path:string,body:unknown={},token?:string){const r=await app.inject({method:'POST',url:path,payload:JSON.stringify(body),headers:token?{authorization:`Bearer ${token}`,'content-type':'application/json'}:{'content-type':'application/json'}});return {status:r.statusCode,...r.json()};}
async function owner(){const invitation=await bootstrapCloud(pool);return (await call('/v1/auth/redeem',{code:invitation.code,username:'Owner',password:'long secure password!',name:'Owner'})).data;}
test('remembered human login survives normal time expiry but logout revokes it',async()=>{
 const o=await owner();expect(o.expires_at).toBe('9999-12-31T23:59:59.000Z');
 const {Service}=await import('../../packages/core/src/service.ts');const service=new Service(pool,'cloud');
 expect((await service.authenticate(o.token)).human_id).toBe(o.profile.id);
 expect((await call('/v1/auth/logout',{},o.token)).status).toBe(200);
 await expect(service.authenticate(o.token)).rejects.toMatchObject({code:'UNAUTHORIZED'});
});
test('owner code is hashed, one-time, and login username normalized',async()=>{const code=await bootstrapCloud(pool);const body={code:code.code,username:'Owner',password:'long secure password!',name:'Owner'};const result=await call('/v1/auth/redeem',body);expect(result.status).toBe(200);expect((await call('/v1/auth/redeem',body)).status).toBe(409);expect((await call('/v1/auth/login',{username:'OWNER',password:body.password})).status).toBe(200);expect((await pool.query('SELECT code_hash FROM graybox.invitations')).rows[0].code_hash).not.toBe(code.code);});
test('concurrent redemption has one winner',async()=>{const code=await bootstrapCloud(pool);const results=await Promise.all(['a','b'].map(s=>call('/v1/auth/redeem',{code:code.code,username:`user_${s}`,password:'long secure password!',name:s})));expect(results.map(x=>x.status).sort()).toEqual([200,409]);});
test('agent approval binds human and retrieval consumes credential once',async()=>{const o=await owner();const pair=(await call('/v1/auth/pair/start',{name:'Agent'})).data;expect((await call('/v1/agents/pair/approve',{user_code:pair.user_code,project_ids:null},o.token)).status).toBe(200);const approved=await call('/v1/auth/pair/poll',{device_code:pair.device_code});expect(approved.data.human_id).toBe(o.profile.id);expect(approved.data.status).toBe('approved');expect((await call('/v1/auth/pair/poll',{device_code:pair.device_code})).status).toBe(409);expect((await call('/v1/members/invite',{},approved.data.token)).status).toBe(401);});
test('member disable invalidates sessions and owner cannot be disabled',async()=>{const o=await owner();const invite=(await call('/v1/members/invite',{},o.token)).data;const m=(await call('/v1/auth/redeem',{code:invite.code,username:'member',password:'long secure password!',name:'Member'})).data;expect((await call(`/v1/members/${o.profile.id}/disable`,{},o.token)).status).toBe(403);expect((await call(`/v1/members/${m.profile.id}/disable`,{},o.token)).status).toBe(200);expect((await call('/v1/members/invite',{},m.token)).status).toBe(401);});
test('expired credential rejected and stale principal cannot write',async()=>{const o=await owner();const {Service}=await import('../../packages/core/src/service.ts');const service=new Service(pool,'cloud');const p=await service.authenticate(o.token);await pool.query('UPDATE graybox.credentials SET expires_at=now()-interval \'1 second\' WHERE id=$1',[p.id]);await expect(service.authenticate(o.token)).rejects.toMatchObject({code:'UNAUTHORIZED'});await expect(service.command(p,{type:'project_create',payload:{workspace_id:o.workspace_id,name:'No'},batch_id:crypto.randomUUID(),idempotency_key:crypto.randomUUID()})).rejects.toMatchObject({code:'UNAUTHORIZED'});});
test('strict requests and rate limits bound public authentication',async()=>{expect((await call('/v1/auth/pair/start',{name:'Agent',human_id:crypto.randomUUID()})).status).toBe(400);for(let i=0;i<30;i++)await call('/v1/auth/pair/poll',{device_code:'x'.repeat(43)});expect((await call('/v1/auth/pair/poll',{device_code:'x'.repeat(43)})).status).toBe(429);});
test('team cap remains atomic when final slots race',async()=>{const o=await owner();for(let i=0;i<2;i++){const invite=(await call('/v1/members/invite',{},o.token)).data;expect((await call('/v1/auth/redeem',{code:invite.code,username:`member${i}`,password:'long secure password!',name:'Member'})).status).toBe(200);}const codes=await Promise.all([call('/v1/members/invite',{},o.token),call('/v1/members/invite',{},o.token)]);const results=await Promise.all(codes.map((r,i)=>call('/v1/auth/redeem',{code:r.data.code,username:`extra${i}`,password:'long secure password!',name:'Extra'})));expect(results.map(r=>r.error.code)).toEqual(['MEMBER_LIMIT','MEMBER_LIMIT']);expect((await pool.query('SELECT count(*)::int n FROM graybox.users')).rows[0].n).toBe(3);});
test('expired invites and pairs reject, unknown project cannot approve',async()=>{const o=await owner();const invite=(await call('/v1/members/invite',{},o.token)).data;await pool.query('UPDATE graybox.invitations SET expires_at=now()-interval \'1 second\' WHERE used_at IS NULL');expect((await call('/v1/auth/redeem',{code:invite.code,username:'expired',password:'long secure password!',name:'Expired'})).error.code).toBe('INVALID_CODE');const pair=(await call('/v1/auth/pair/start',{name:'Agent'})).data;expect((await call('/v1/agents/pair/approve',{user_code:pair.user_code,project_ids:[crypto.randomUUID()]},o.token)).status).toBe(400);await pool.query('UPDATE graybox.pairs SET expires_at=now()-interval \'1 second\'');expect((await call('/v1/auth/pair/poll',{device_code:pair.device_code})).error.code).toBe('INVALID_CODE');});
test('bad login outcomes generic and logout immediately revokes',async()=>{const o=await owner();const wrong=await call('/v1/auth/login',{username:'owner',password:'wrong long password'});const unknown=await call('/v1/auth/login',{username:'unknown',password:'wrong long password'});expect(wrong.error).toEqual(unknown.error);expect((await call('/v1/auth/logout',{},o.token)).status).toBe(200);expect((await app.inject({method:'GET',url:'/v1/auth/me',headers:{authorization:`Bearer ${o.token}`}})).statusCode).toBe(401);});
test('expiry is revalidated after waiting for write lock',async()=>{const o=await owner();const {Service}=await import('../../packages/core/src/service.ts');const service=new Service(pool,'cloud');const p=await service.authenticate(o.token);await pool.query('UPDATE graybox.credentials SET expires_at=clock_timestamp()+interval \'200 milliseconds\' WHERE id=$1',[p.id]);const lock=await pool.connect();try{await lock.query('BEGIN');await lock.query('SELECT pg_advisory_xact_lock(77321)');const write=service.command(p,{type:'project_create',payload:{workspace_id:o.workspace_id,name:'No'},batch_id:crypto.randomUUID(),idempotency_key:crypto.randomUUID()});const observed=expect(write).rejects.toMatchObject({code:'UNAUTHORIZED'});await new Promise(r=>setTimeout(r,400));await lock.query('COMMIT');await observed;}finally{await lock.query('ROLLBACK');lock.release();}});
test('loopback proxy forwarded clients receive separate rate buckets',async()=>{for(let i=0;i<31;i++)await app.inject({method:'POST',url:'/v1/auth/pair/poll',remoteAddress:'127.0.0.1',headers:{'x-forwarded-for':'203.0.113.1'},payload:{device_code:'x'.repeat(43)}});const other=await app.inject({method:'POST',url:'/v1/auth/pair/poll',remoteAddress:'127.0.0.1',headers:{'x-forwarded-for':'203.0.113.2'},payload:{device_code:'x'.repeat(43)}});expect(other.statusCode).toBe(409);});
test('nonloopback direct caller cannot evade limits with spoofed forwarding',async()=>{for(let i=0;i<30;i++)await app.inject({method:'POST',url:'/v1/auth/pair/poll',remoteAddress:'203.0.113.1',headers:{'x-forwarded-for':`198.51.100.${i}`},payload:{device_code:'x'.repeat(43)}});const spoof=await app.inject({method:'POST',url:'/v1/auth/pair/poll',remoteAddress:'203.0.113.1',headers:{'x-forwarded-for':'198.51.100.99'},payload:{device_code:'x'.repeat(43)}});expect(spoof.statusCode).toBe(429);});
test('server port defaults to4318 accepts4328 and rejects invalid ports',async()=>{const api=await import('../../apps/api/src/app.ts');const parsePort=(api as unknown as {parseServerPort:(s?:string)=>number}).parseServerPort;expect(parsePort()).toBe(4318);expect(parsePort('4328')).toBe(4328);for(const bad of ['','0','65536','1.5','-1',' 4328','4328abc'])expect(()=>parsePort(bad)).toThrow('port');});
