import {beforeAll,beforeEach,afterAll,test,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {config} from 'dotenv';
import {buildApp} from '../../apps/api/src/app.ts';
import {migrate} from '../../packages/db/src/migrate.ts';
import {seedDatabase} from '../../packages/db/src/seed.ts';
config({quiet:true});
for(const key of ['GRAYBOX_TEST_DATABASE_URL','GRAYBOX_TEST_ADMIN_URL'])if(new URL(process.env[key]!).pathname!=='/graybox_test')throw Error('Isolated test DB required');
const admin=new Pool({connectionString:process.env.GRAYBOX_TEST_ADMIN_URL}),runtime=new Pool({connectionString:process.env.GRAYBOX_TEST_DATABASE_URL});
let app:Awaited<ReturnType<typeof buildApp>>,f:Awaited<ReturnType<typeof seedDatabase>>;
const body=(type:string,payload:unknown,revision?:number,batch_id:string=randomUUID())=>({type,payload,batch_id,idempotency_key:randomUUID(),...(revision?{expected_revision:revision}:{})});
async function req(method:'GET'|'POST',url:string,payload?:unknown,token=f.tokens.member_agent){const r=await app.inject({method,url,headers:{authorization:`Bearer ${token}`},...(payload?{payload}: {})});return {status:r.statusCode,...r.json()};}
async function cmd(type:string,payload:unknown,revision?:number,token=f.tokens.member_agent,batch?:string){return req('POST','/v1/commands',body(type,payload,revision,batch),token);}
async function project(extra={}){return (await cmd('project_create',{workspace_id:f.workspace_id,name:'P',...extra})).data;}
beforeAll(async()=>{app=await buildApp({pool:runtime,mode:'local'});});
beforeEach(async()=>{await admin.query('DROP SCHEMA IF EXISTS graybox CASCADE');await migrate(admin);f=await seedDatabase(admin);});
afterAll(async()=>{await app?.close();await runtime.end();await admin.end();});
test('projects default todo/medium and expose creator identity',async()=>{const p=await project();expect(p.lifecycle).toBe('todo');expect(p.priority).toBe('medium');expect(p.creator_id).toBe(f.humans[1]!.id);expect(p.can_edit).toBe(true);});
test('priority ordering and shared normalized tag catalog',async()=>{const low=await project({priority:'low',tags:['  Web   App ','web app']});const high=await project({priority:'high',tags:['WEB APP']});expect((await req('GET','/v1/projects')).data.map((p:any)=>p.id)).toEqual([high.id,low.id]);expect(low.tags).toEqual(['Web App']);expect((await req('GET','/v1/projects?tag=web%20app')).data).toHaveLength(2);await cmd('project_update',{id:low.id,tags:[]},1);expect((await req('GET','/v1/tags')).data).toHaveLength(1);});
test('other members read/comment but only the project creator can mutate',async()=>{const p=await project();expect((await req('GET',`/v1/projects/${p.id}`,undefined,f.tokens.third_agent)).data.can_edit).toBe(false);expect((await cmd('project_update',{id:p.id,name:'X'},1,f.tokens.third_agent)).status).toBe(403);const r=await cmd('comment_create',{project_id:p.id,body:'Hi'},1,f.humans[2]!.token);expect(r.status).toBe(200);expect(r.data.author_id).toBe(f.humans[2]!.id);expect(r.data.project_revision).toBe(2);expect((await req('GET',`/v1/projects/${p.id}/comments`)).data).toHaveLength(1);expect((await cmd('project_update',{id:p.id,name:'No global bypass'},2,f.tokens.owner_agent)).status).toBe(403);expect((await cmd('project_update',{id:p.id,name:'Owner'},2,f.tokens.member_agent)).status).toBe(200);});
const report=(id:string)=>({project_id:id,title:'Attempt',goal:'G',approach:'A',result:'R',verification:'Not run',failures:'F',reusable:'U',lessons:'L',next_steps:'N',outcome:'inconclusive',custom_sections:[]});
test('immutable reports validate bounds, identity, revisions and idempotency',async()=>{const p=await project();const b=body('retrospective_create',report(p.id),1);const r=await req('POST','/v1/commands',b);expect(r.status).toBe(200);expect(r.data.author_id).toBe(f.humans[1]!.id);expect(r.data.agent_id).toBe(f.agents[1]!.id);expect(await req('POST','/v1/commands',b)).toEqual(r);expect((await cmd('comment_create',{project_id:p.id,body:'stale'},1)).error.code).toBe('REVISION_CONFLICT');expect((await cmd('retrospective_create',{...report(p.id),goal:'x'.repeat(12001)},2)).status).toBe(400);expect((await cmd('retrospective_create',report(p.id),2,f.tokens.third_agent)).status).toBe(403);expect((await req('GET',`/v1/projects/${p.id}/retrospectives`)).data).toHaveLength(1);expect((await req('GET',`/v1/projects/${p.id}/comments`,undefined,f.tokens.restricted_agent)).status).toBe(404);});
test('undo fails closed for immutable children and never partially changes batch',async()=>{const batch=randomUUID();const p=(await cmd('project_create',{workspace_id:f.workspace_id,name:'P'},undefined,f.tokens.member_agent,batch)).data;await cmd('comment_create',{project_id:p.id,body:'Hi'},1,f.tokens.member_agent,batch);const pr=await req('POST',`/v1/batches/${batch}/preview`,{});expect(pr.status).toBe(409);expect(pr.error.code).toBe('UNDO_UNAVAILABLE');expect((await req('GET',`/v1/projects/${p.id}`)).data.revision).toBe(2);});
test('migration replays preserve environment and backfill original creator',async()=>{const p=await project();await admin.query('UPDATE graybox.projects SET creator_id=NULL,data=data-\'lifecycle\'-\'priority\'-\'tags\' WHERE id=$1',[p.id]);const env=(await admin.query('SELECT value FROM graybox.metadata')).rows;await migrate(admin);await migrate(admin);expect((await req('GET',`/v1/projects/${p.id}`)).data.creator_id).toBe(f.humans[1]!.id);expect((await req('GET',`/v1/projects/${p.id}`)).data.lifecycle).toBe('in_progress');expect((await admin.query('SELECT value FROM graybox.metadata')).rows).toEqual(env);});

test('tag removal retains catalog with no remaining association and supports search/workspace filters',async()=>{const p=await project({tags:['  Research  ','research','RESEARCH','Two   Words']});expect(p.tags).toEqual(['Research','Two Words']);await cmd('project_update',{id:p.id,tags:[]},1);expect((await req('GET','/v1/tags?q=research')).data).toHaveLength(1);expect((await req('GET','/v1/projects?tag=research')).data).toEqual([]);expect((await req('GET',`/v1/tags?workspace_id=${randomUUID()}`)).data).toEqual([]);});
test('scoped agents cannot discover tags or child data outside scope',async()=>{const p=await project({tags:['Private scope']});await cmd('comment_create',{project_id:p.id,body:'Hi'},1);expect((await req('GET','/v1/tags',undefined,f.tokens.restricted_agent)).data).toEqual([]);expect((await cmd('comment_create',{project_id:p.id,body:'No'},2,f.tokens.restricted_agent)).status).toBe(404);});
test('custom section boundaries reject forged identity and unknown fields',async()=>{const p=await project();for(const extra of [{author_id:f.humans[0]!.id},{custom_sections:Array.from({length:21},()=>({title:'x',content:''}))},{custom_sections:[{title:'',content:'x'}]},{custom_sections:[{title:'x',content:'y'.repeat(12001)}]}])expect((await cmd('retrospective_create',{...report(p.id),...extra},1)).status).toBe(400);});
test('later children prevent undo of creation even with already signed preview',async()=>{const batch=randomUUID();const p=(await cmd('project_create',{workspace_id:f.workspace_id,name:'P'},undefined,f.tokens.member_agent,batch)).data;const pr=await req('POST',`/v1/batches/${batch}/preview`,{});await cmd('comment_create',{project_id:p.id,body:'Other member discussion'},1,f.humans[2]!.token);const r=await req('POST',`/v1/batches/${batch}/undo`,{expected_batch_revision:pr.data.batch_revision,preview_token:pr.data.preview_token,idempotency_key:randomUUID()});expect(r.status).toBe(409);expect((await req('GET',`/v1/projects/${p.id}/comments`)).data).toHaveLength(1);expect((await admin.query('SELECT count(*)::int n FROM graybox.batches WHERE compensates=$1',[batch])).rows[0].n).toBe(0);});
test('undo metadata restores lifecycle/priority/tags without deleting catalog',async()=>{const p=await project({tags:['A']});const batch=randomUUID();await cmd('project_update',{id:p.id,lifecycle:'completed',priority:'high',tags:['B']},1,f.tokens.member_agent,batch);const pr=await req('POST',`/v1/batches/${batch}/preview`,{});expect((await req('POST',`/v1/batches/${batch}/undo`,{expected_batch_revision:pr.data.batch_revision,preview_token:pr.data.preview_token,idempotency_key:randomUUID()})).status).toBe(200);const restored=(await req('GET',`/v1/projects/${p.id}`)).data;expect(restored.lifecycle).toBe('todo');expect(restored.priority).toBe('medium');expect(restored.tags).toEqual(['A']);expect((await req('GET','/v1/tags')).data).toHaveLength(2);});
test('legacy creator without original creation audit stays unassigned and read-only; lifecycle mapping preserves rows',async()=>{for(const status of ['active','paused','archived']){const id=randomUUID();await admin.query('INSERT INTO graybox.projects(id,workspace_id,revision,data) VALUES($1,$2,4,$3)',[id,f.workspace_id,{name:status,status,description:'Legacy'}]);}await migrate(admin);const rows=(await req('GET','/v1/projects')).data;expect(rows.map((p:any)=>p.lifecycle).sort()).toEqual(['completed','in_progress','paused']);for(const p of rows){expect(p.creator_id).toBe(null);expect(p.can_edit).toBe(false);expect(p.revision).toBe(4);expect((await cmd('project_update',{id:p.id,name:'No'},4)).status).toBe(403);expect(p.project_role).toBe('member');expect((await cmd('project_update',{id:p.id,name:'Owner'},4,f.tokens.owner_agent)).status).toBe(403);}});
test('runtime cannot update/delete reports comments tags or forge creator through contract',async()=>{const p=await project();expect((await cmd('project_update',{id:p.id,creator_id:f.humans[0]!.id},1)).status).toBe(400);for(const sql of ['UPDATE graybox.retrospectives SET data=data','DELETE FROM graybox.retrospectives','UPDATE graybox.comments SET body=body','DELETE FROM graybox.comments','DELETE FROM graybox.tags'])await expect(runtime.query(sql)).rejects.toHaveProperty('code','42501');});

test('undo of historical metadata audit fills library defaults while preserving original status',async()=>{const p=await project();const batch=randomUUID();await cmd('project_update',{id:p.id,name:'Changed'},1,f.tokens.member_agent,batch);await admin.query("UPDATE graybox.activities SET before=before-'lifecycle'-'priority'-'tags' WHERE batch_id=$1 AND entity_type='project'",[batch]);const pr=await req('POST',`/v1/batches/${batch}/preview`,{});await req('POST',`/v1/batches/${batch}/undo`,{expected_batch_revision:pr.data.batch_revision,preview_token:pr.data.preview_token,idempotency_key:randomUUID()});const restored=(await req('GET',`/v1/projects/${p.id}`)).data;expect(restored.lifecycle).toBe('in_progress');expect(restored.priority).toBe('medium');expect(restored.tags).toEqual([]);});

test('former project owner cannot preview or execute historical metadata undo',async()=>{
  const token=f.tokens.owner_agent,p=(await cmd('project_create',{workspace_id:f.workspace_id,name:'P'},undefined,token)).data,batch=randomUUID();
  expect((await cmd('project_update',{id:p.id,name:'Owner edit'},1,token,batch)).status).toBe(200);
  const pr=await req('POST',`/v1/batches/${batch}/preview`,{},token);
  expect(pr.status).toBe(200);
  await admin.query("UPDATE graybox.projects SET creator_id=NULL WHERE id=$1",[p.id]);
  expect((await cmd('project_update',{id:p.id,name:'Forbidden'},2,token)).status).toBe(403);
  const preview=await req('POST',`/v1/batches/${batch}/preview`,{},token);
  const undo=await req('POST',`/v1/batches/${batch}/undo`,{expected_batch_revision:pr.data.batch_revision,preview_token:pr.data.preview_token,idempotency_key:randomUUID()},token);
  expect(preview.status).toBe(403);expect(preview.error.code).toBe('FORBIDDEN');
  expect(undo.status).toBe(403);expect(undo.error.code).toBe('FORBIDDEN');
  const unchanged=(await req('GET',`/v1/projects/${p.id}`)).data;
  expect(unchanged.name).toBe('Owner edit');expect(unchanged.revision).toBe(2);
  expect((await admin.query('SELECT count(*)::int n FROM graybox.batches WHERE compensates=$1',[batch])).rows[0].n).toBe(0);
});

test('successful undo receipt remains replayable after project authority loss',async()=>{
  const token=f.tokens.owner_agent,p=(await cmd('project_create',{workspace_id:f.workspace_id,name:'P'},undefined,token)).data,batch=randomUUID();
  await cmd('project_update',{id:p.id,name:'Owner edit'},1,token,batch);
  const pr=await req('POST',`/v1/batches/${batch}/preview`,{},token);
  const input={expected_batch_revision:pr.data.batch_revision,preview_token:pr.data.preview_token,idempotency_key:randomUUID()};
  const receipt=await req('POST',`/v1/batches/${batch}/undo`,input,token);expect(receipt.status).toBe(200);
  await admin.query("UPDATE graybox.projects SET creator_id=NULL WHERE id=$1",[p.id]);
  expect(await req('POST',`/v1/batches/${batch}/undo`,input,token)).toEqual(receipt);
  expect((await req('GET',`/v1/projects/${p.id}`)).data.revision).toBe(3);
});
