import React,{useEffect,useRef,useState} from 'react';
import {request,attachmentTransfer,sessionGeneration,ApiError,connection} from './platform.ts';
import {writeSafety} from './write-safety.ts';
import {checkFile,demoSandbox,type Attachment,type AttachmentTarget} from './attachment-model.ts';
import './attachments.css';
type Job={metadata:Record<string,unknown>;bytes?:Uint8Array;storageKey:string;running?:boolean};
const jobs=new Map<string,Job>();
const listeners=new Set<()=>void>();
const notifyJobs=()=>{for(const listener of listeners)listener();};
const decode=(text:string)=>Uint8Array.from(atob(text),c=>c.charCodeAt(0));
const definitive=(e:unknown)=>e instanceof ApiError&&['VALIDATION','FORBIDDEN','UNAUTHORIZED','NOT_FOUND','IDEMPOTENCY_MISMATCH','UPLOAD_TOO_LARGE','PAYLOAD_TOO_LARGE','QUOTA_EXCEEDED','UNSUPPORTED_MEDIA','HASH_MISMATCH','DIGEST_MISMATCH'].includes(e.code);
export function Attachments({profile,target,editable,refreshVersion=0}:{profile:string;target:AttachmentTarget;editable:boolean;refreshVersion?:number}) {
 const targetKey=`${profile}:${target.entity_type}:${target.entity_id}`,alive=useRef(true),preparing=useRef(false);
 const [items,setItems]=useState<Attachment[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reading,setReading]=useState(true),[busy,setBusy]=useState(false),[caption,setCaption]=useState(''),[file,setFile]=useState<File|null>(null),[link,setLink]=useState(''),[linkKind,setLinkKind]=useState<'repository'|'demo_link'>('repository'),[version,setVersion]=useState(0),[retry,setRetry]=useState(()=>jobs.has(targetKey)),[preview,setPreview]=useState<{item:Attachment;url?:string;src?:string;urls:string[]}|null>(null);
 useEffect(()=>{let previous=jobs.has(targetKey);const sync=()=>{const present=jobs.has(targetKey);if(previous&&!present)setVersion(v=>v+1);previous=present;setRetry(present);setBusy(preparing.current||!!jobs.get(targetKey)?.running);};listeners.add(sync);sync();return()=>{listeners.delete(sync);};},[targetKey]);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{let active=true;setReading(true);setError('');request<Attachment[]>(profile,`/v1/attachments?entity_type=${target.entity_type}&entity_id=${target.entity_id}`).then(v=>{if(active)setItems(v);}).catch(e=>{if(active)setError((e as Error).message);}).finally(()=>{if(active)setReading(false);});return()=>{active=false;};},[profile,targetKey,version,refreshVersion]);
 useEffect(()=>()=>{for(const url of preview?.urls??[])URL.revokeObjectURL(url);},[preview]);
 async function send(job:Job) {
  if(job.running)return;setBusy(true);setError('');setNotice('');const generation=sessionGeneration();let attempt:ReturnType<typeof writeSafety.begin>|undefined;
  try {
   attempt=writeSafety.begin(profile,'/v1/attachments/'+(job.bytes?'upload':'link'),job.metadata,generation);job.running=true;jobs.set(targetKey,job);notifyJobs();
   const result=(job.bytes?await attachmentTransfer(profile,'/v1/attachments/upload',job.bytes,job.metadata):await request(profile,'/v1/attachments/link','POST',job.metadata)) as Attachment;
   const checked=await request<Attachment[]>(profile,`/v1/attachments?entity_type=${target.entity_type}&entity_id=${target.entity_id}`);
   if(generation!==sessionGeneration()||!checked.some(a=>a.id===result.id&&(job.bytes?a.sha256===job.metadata.sha256:a.url===job.metadata.url)))throw new Error('上传结果尚未核对，请重试原操作。');
   writeSafety.finish(attempt,true);jobs.delete(targetKey);notifyJobs();localStorage.removeItem(job.storageKey);
   if(alive.current){setItems(checked);setRetry(false);setFile(null);setCaption('');setLink('');setNotice('已添加');}
  }catch(e){if(attempt)writeSafety.finish(attempt,false,definitive(e));if(definitive(e)&&!writeSafety.snapshot()){jobs.delete(targetKey);notifyJobs();localStorage.removeItem(job.storageKey);}if(alive.current){setRetry(jobs.has(targetKey));setError((e as Error).message);}}
  finally{job.running=false;notifyJobs();if(alive.current)setBusy(false);}
 }
 async function upload(){if(!file||preparing.current||jobs.has(targetKey))return;preparing.current=true;setBusy(true);try{const kind=checkFile(file.name,file.size),bytes=new Uint8Array(await file.arrayBuffer()),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join(''),storageKey=`graybox-attachment:${targetKey}:${hash}`;
   if(!localStorage.getItem(storageKey)&&items.some(a=>a.sha256===hash)){setNotice('这个文件已上传');return;}
   let metadata:Record<string,unknown>|undefined;const saved=localStorage.getItem(storageKey);if(saved){const old=JSON.parse(saved);if(old.sha256===hash&&old.entity_id===target.entity_id&&old.entity_type===target.entity_type&&typeof old.idempotency_key==='string')metadata=old;}
   metadata??={...target,idempotency_key:crypto.randomUUID(),name:file.name,caption,kind,sha256:hash};
   localStorage.setItem(storageKey,JSON.stringify(metadata));const job={metadata,bytes,storageKey};await send(job);
  }catch(e){if(alive.current)setError((e as Error).message);}finally{preparing.current=false;if(alive.current)setBusy(!!jobs.get(targetKey)?.running);}}
 async function addLink(){if(preparing.current||jobs.has(targetKey))return;preparing.current=true;setBusy(true);try{const url=new URL(link);if(!localStorage.getItem(`graybox-attachment:${targetKey}:link:${url.href}`)&&items.some(a=>a.url===url.href&&a.kind===linkKind)){setNotice('这个链接已添加');return;}if(url.protocol!=='https:'||url.username||url.password)throw new Error('请填写不含账号密码的 HTTPS 地址。');const storageKey=`graybox-attachment:${targetKey}:link:${url.href}`,old=localStorage.getItem(storageKey),metadata=old?JSON.parse(old):{...target,idempotency_key:crypto.randomUUID(),name:linkKind==='repository'?'源码仓库':'在线演示',caption,kind:linkKind,url:url.href};localStorage.setItem(storageKey,JSON.stringify(metadata));const job={metadata,storageKey};await send(job);}catch(e){if(alive.current)setError((e as Error).message);}finally{preparing.current=false;if(alive.current)setBusy(!!jobs.get(targetKey)?.running);}}
 async function open(item:Attachment){setError('');const generation=sessionGeneration();let urls:string[]=[];try{if(item.kind==='demo'){const result=await request<{url:string}>(profile,`/v1/attachments/${item.id}/preview`,'POST',{}),c=await connection();if(!/^\/v1\/attachment-previews\/[A-Za-z0-9_-]+$/.test(result.url))throw new Error('演示地址不正确。');if(!alive.current||generation!==sessionGeneration())return;setPreview({item,src:c.endpoint+result.url,urls:[]});return;}const result=await attachmentTransfer(profile,`/v1/attachments/${item.id}/content`) as {base64:string;mime_type:string};if(!alive.current||generation!==sessionGeneration())return;const bytes=decode(result.base64),url=URL.createObjectURL(new Blob([bytes],{type:item.mime_type}));urls=[url];setPreview({item,url,urls});}catch(e){for(const url of urls)URL.revokeObjectURL(url);if(alive.current)setError((e as Error).message);}}
 return <section className="gb-attachments" aria-label="附件与链接"><header><h3>附件与链接</h3><button disabled={busy||reading} onClick={()=>setVersion(v=>v+1)}>刷新附件</button></header>
  {reading&&<p role="status">正在读取附件…</p>}{error&&<p role="alert" className="gb-attachment-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
  <div className="gb-attachment-list">{items.map(item=><article key={item.id}><strong>{item.name}</strong><small>{item.caption||({image:'图片',video:'视频',demo:'网页演示',repository:'源码仓库',demo_link:'在线演示'}[item.kind])}{item.byte_size>0&&` · ${(item.byte_size/1024/1024).toFixed(1)} MB`}</small>{item.url?<a href={item.url} target="_blank" rel="noopener noreferrer">{item.kind==='repository'?'打开仓库':'打开演示'} ↗</a>:<button onClick={()=>void open(item)}>{item.kind==='image'?'查看图片':item.kind==='video'?'播放视频':'打开演示'}</button>}</article>)}</div>
  {!reading&&!items.length&&<p className="cw-muted">暂无附件</p>}
  {editable&&!retry&&Object.keys(localStorage).some(k=>k.startsWith(`graybox-attachment:${targetKey}:`))&&<p role="status">有附件操作尚未核对。重新选择原文件或填写原链接，继续核对。</p>}
  {editable&&<div className="gb-attachment-form"><label>说明<input value={caption} maxLength={1000} disabled={busy||retry} onChange={e=>setCaption(e.target.value)} placeholder="例如：第二次实验效果"/></label><div><label className="gb-file-picker">选择图片、视频或 HTML<input type="file" accept=".png,.jpg,.jpeg,.webp,.mp4,.webm,.html,.htm" disabled={busy||retry} onChange={e=>{setFile(e.target.files?.[0]??null);setError('');}}/></label><button disabled={!file||busy||retry||!!writeSafety.snapshot()} onClick={()=>void upload()}>{busy?'正在上传…':'上传附件'}</button></div><small>图片 ≤10 MB，视频 ≤50 MB，自包含网页 ≤5 MB</small><div><select value={linkKind} disabled={busy||retry} onChange={e=>setLinkKind(e.target.value as typeof linkKind)}><option value="repository">GitHub / 源码仓库</option><option value="demo_link">在线演示</option></select><input type="url" value={link} disabled={busy||retry} onChange={e=>setLink(e.target.value)} placeholder="https://…"/><button disabled={!link.trim()||busy||retry||!!writeSafety.snapshot()} onClick={()=>void addLink()}>添加链接</button></div>{retry&&<button disabled={busy} onClick={()=>{const job=jobs.get(targetKey);if(job)void send(job);}}>重试原附件操作</button>}</div>}
  {preview&&<PreviewDialog name={preview.item.name} close={()=>setPreview(null)}><div className="gb-attachment-preview"><header><strong>{preview.item.name}</strong><button autoFocus onClick={()=>setPreview(null)}>关闭预览</button></header>{preview.item.kind==='image'?<img src={preview.url} alt={preview.item.caption||preview.item.name}/>:preview.item.kind==='video'?<video src={preview.url} controls playsInline/>:<iframe title={preview.item.name} sandbox={demoSandbox} referrerPolicy="no-referrer" src={preview.src}/>}</div></PreviewDialog>}
 </section>;
}

function PreviewDialog({name,close,children}:{name:string;close:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>{ref.current?.close();previous?.focus();};},[]);return <dialog ref={ref} className="gb-attachment-overlay" aria-label={name} onCancel={e=>{e.preventDefault();close();}}>{children}</dialog>;}
