import {createHash,randomUUID} from 'node:crypto';
import {mkdir,open,readFile,rename,rm,lstat,realpath} from 'node:fs/promises';
import {basename,dirname,isAbsolute,join} from 'node:path';
import {z} from 'zod';
import {ClientError} from '../../client/src/client.ts';
import type {Attachment,UploadMetadata} from '../../core/src/attachments.ts';
import {resolveContext,type ContextOptions} from './binding.ts';
import {gitRoot} from './git.ts';
export const attachmentTarget=z.strictObject({entity_type:z.enum(['project','idea','experiment']),entity_id:z.uuid()});
export const attachmentUploadInput=attachmentTarget.extend({path:z.string().min(1),caption:z.string().max(2000).default('')});
export const attachmentLinkInput=attachmentTarget.extend({name:z.string().min(1).max(200),caption:z.string().max(2000).default(''),kind:z.enum(['repository','demo_link']),url:z.url().max(2048)});
const canonical=(value:unknown):string=>value&&typeof value==='object'?JSON.stringify(Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,JSON.parse(canonical(v))]))):JSON.stringify(value);
const hash=(value:unknown)=>createHash('sha256').update(canonical(value)).digest('hex');
function fail(code:string,message:string):never{throw new ClientError(code,message);}
type Payload=Record<string,unknown>;
type Receipt={operation_id:string;payload:Payload;state:'pending'|'verified';response?:Attachment;verified_at?:string};
/** Independent of business sync cursors; stores no credentials or file bytes. */
export class AttachmentJournal {
 readonly path:string;
 constructor(configPath:string,readonly scope:Record<string,string>){this.path=join(dirname(configPath),'attachment-receipts',hash(scope)+'.json');}
 async read():Promise<Receipt[]>{try{const text=await readFile(this.path,'utf8');if(text.length>4*1024*1024)throw Error();const parsed=z.strictObject({version:z.literal(1),scope:z.record(z.string(),z.string()),receipts:z.array(z.strictObject({operation_id:z.uuid(),payload:z.record(z.string(),z.unknown()),state:z.enum(['pending','verified']),response:z.record(z.string(),z.unknown()).optional(),verified_at:z.string().optional()}))}).parse(JSON.parse(text));if(hash(parsed.scope)!==hash(this.scope))throw Error();return parsed.receipts as Receipt[];}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return [];fail('ATTACHMENT_JOURNAL_INVALID','Preserve invalid attachment journal for explicit recovery');}}
 private async mutate<T>(fn:(receipts:Receipt[])=>Promise<T>|T){await mkdir(dirname(this.path),{recursive:true,mode:0o700});let lock;try{lock=await open(this.path+'.lock','wx',0o600);}catch{fail('ATTACHMENT_BUSY','Another attachment operation owns the journal; retry after it finishes');}const temp=this.path+'.'+randomUUID()+'.tmp';try{const receipts=await this.read(),result=await fn(receipts),text=JSON.stringify({version:1,scope:this.scope,receipts});if(text.length>4*1024*1024)fail('ATTACHMENT_JOURNAL_FULL','Preserve and explicitly archive verified receipts');const file=await open(temp,'wx',0o600);try{await file.writeFile(text);await file.sync();}finally{await file.close();}await rename(temp,this.path);return result;}finally{await rm(temp,{force:true});await lock.close();await rm(this.path+'.lock',{force:true});}}
 prepare(payload:Payload){return this.mutate(receipts=>{let receipt=receipts.find(r=>hash(r.payload)===hash(payload));if(!receipt){receipt={operation_id:randomUUID(),payload,state:'pending'};receipts.push(receipt);}return receipt;});}
 execute(operation_id:string,write:(metadata:Payload&{idempotency_key:string})=>Promise<Attachment>,list:()=>Promise<Attachment[]>){return this.mutate(async receipts=>{const receipt=receipts.find(r=>r.operation_id===operation_id);if(!receipt)fail('ATTACHMENT_MISSING','Durably prepare attachment before sending');const response=receipt.response??await write({...receipt.payload,idempotency_key:receipt.operation_id});if(Object.entries(receipt.payload).some(([key,value])=>canonical((response as unknown as Payload)[key])!==canonical(value)))fail('ATTACHMENT_UNVERIFIED','Server attachment metadata differs from durable intended payload');const actual=(await list()).find(a=>a.id===response.id);if(!actual||hash(actual)!==hash(response))fail('ATTACHMENT_UNVERIFIED','Remote attachment read-back differs; retain original retry key');receipt.response=response;receipt.state='verified';receipt.verified_at=new Date().toISOString();return receipt;});}
}
async function targetContext(options:ContextOptions,target:z.infer<typeof attachmentTarget>){const ctx=await resolveContext(options);if(target.entity_type==='project'){if(target.entity_id!==ctx.project.id)fail('PROJECT_MISMATCH','Attachment target differs from bound project');}else{const entity=target.entity_type==='idea'?await ctx.api.idea(target.entity_id):await ctx.api.experiment(target.entity_id);if(entity.project_id&&entity.project_id!==ctx.project.id)fail('PROJECT_MISMATCH','Attachment target belongs to another project');if(target.entity_type==='idea'&&entity.workspace_id!==ctx.binding.workspace_id)fail('WORKSPACE_MISMATCH','Attachment idea belongs to another workspace');}return ctx;}
export async function attachmentList(options:ContextOptions,input:unknown){const target=attachmentTarget.parse(input),ctx=await targetContext(options,target);return ctx.api.attachments(target);}
export async function attachmentWrite(options:ContextOptions,input:unknown,kind:'upload'|'link'){
 const parsed=kind==='upload'?attachmentUploadInput.parse(input):attachmentLinkInput.parse(input),ctx=await targetContext(options,parsed);
 // Even local demonstration config cannot put private durable receipts in a repository.
 if(await gitRoot(dirname(await realpath(ctx.config_path))))fail('CONFIG_INVALID','Attachment receipts require trusted config outside repositories');
 let bytes:Buffer|undefined,payload:Payload;
 if('path' in parsed){if(!isAbsolute(parsed.path))fail('PATH_INVALID','Explicit absolute attachment file required');const stat=await lstat(parsed.path);if(!stat.isFile())fail('PATH_INVALID','Attachment must be an existing regular file, not symlink or directory');const ext=basename(parsed.path).split('.').at(-1)?.toLowerCase(),fileKind=['png','jpg','jpeg','webp'].includes(ext??'')?'image':['mp4','webm'].includes(ext??'')?'video':['html','htm'].includes(ext??'')?'demo':fail('VALIDATION','Allowed attachment extension required');const limit=fileKind==='video'?50*1024*1024:fileKind==='demo'?5*1024*1024:10*1024*1024;if(!stat.size||stat.size>limit)fail('PAYLOAD_TOO_LARGE','Attachment exceeds format limit');bytes=await readFile(parsed.path);if(bytes.length!==stat.size)fail('FILE_CHANGED','Attachment changed during read; retry with stable source');payload={entity_type:parsed.entity_type,entity_id:parsed.entity_id,name:basename(parsed.path),caption:parsed.caption,kind:fileKind,sha256:createHash('sha256').update(bytes).digest('hex')};}else payload={...parsed,url:new URL(parsed.url).href};
 const journal=new AttachmentJournal(ctx.config_path,{environment_id:ctx.binding.environment_id,workspace_id:ctx.binding.workspace_id,project_id:ctx.project.id,cwd:ctx.paths.cwd,credential_id:ctx.identity.credential_id,human_id:ctx.identity.human_id,agent_id:ctx.identity.agent_id});
 const receipt=await journal.prepare(payload);
 return journal.execute(receipt.operation_id,metadata=>bytes?ctx.api.uploadAttachment(metadata as UploadMetadata,bytes):ctx.api.linkAttachment(metadata as Parameters<typeof ctx.api.linkAttachment>[0]),async()=>{const fresh=await targetContext(options,parsed);if(fresh.identity.credential_id!==ctx.identity.credential_id)fail('AGENT_MISMATCH','Attachment identity changed during upload');return fresh.api.attachments(parsed);});
}
