import {mkdir,writeFile,readFile,rename,rm,realpath,chmod} from 'node:fs/promises';
import {dirname,join,resolve} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {ApiClient,ClientError,cloudEndpoint} from '../../client/src/client.ts';
import {configFile,readConfig,cloudCredentialsSchema} from './binding.ts';
import {gitRoot} from './git.ts';
const execute=promisify(execFile);
const pendingSchema=z.strictObject({version:z.literal(1),endpoint:z.string(),name:z.string().min(1).max(100),device_code:z.string().min(1).max(512),expires_at:z.iso.datetime(),environment_id:z.uuid()});
const approvedSchema=z.strictObject({status:z.literal('approved'),token:z.string().min(1).max(512),expires_at:z.iso.datetime(),agent_id:z.uuid(),human_id:z.uuid(),workspace_id:z.uuid(),environment_id:z.uuid()});
async function trustedPath(explicit?:string){const path=configFile(explicit);await mkdir(dirname(path),{recursive:true});const actual=await realpath(dirname(path));if(resolve(actual)!==resolve(dirname(path)))throw new ClientError('CONFIG_INVALID','Cloud personal config must not use directory symlinks');if(await gitRoot(actual))throw new ClientError('CONFIG_INVALID','Cloud personal config must be outside a repository');return path;}
async function restrict(path:string){if(process.platform==='win32'){const {stdout}=await execute('powershell.exe',['-NoProfile','-NonInteractive','-Command','[System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value'],{windowsHide:true});const sid=stdout.trim();if(!/^S-1-[0-9-]+$/.test(sid))throw new ClientError('PERMISSIONS_FAILED','Cannot identify Windows account');await execute('icacls.exe',[path,'/inheritance:r','/grant:r',`*${sid}:(F)`],{windowsHide:true});}else await chmod(path,(await (await import('node:fs/promises')).stat(path)).isDirectory()?0o700:0o600);}
async function privateJson(path:string,value:unknown){const directory=path+'.'+randomUUID()+'.private';await mkdir(directory,{mode:0o700});try{await restrict(directory);const temp=join(directory,'value.json');await writeFile(temp,JSON.stringify(value,null,2)+'\n',{flag:'wx',mode:0o600});await restrict(temp);await rename(temp,path);}finally{await rm(directory,{force:true,recursive:true});}}
async function pairRequest(endpoint:string,action:'start'|'poll',body:unknown){let response:Response;try{response=await fetch(cloudEndpoint(endpoint)+'/v1/auth/pair/'+action,{method:'POST',redirect:'manual',signal:AbortSignal.timeout(8000),headers:{'content-type':'application/json'},body:JSON.stringify(body)});}catch{throw new ClientError('CONNECTION_FAILED','Pair request failed or timed out',503);}if(response.status>=300&&response.status<400)throw new ClientError('REDIRECT_REJECTED','Pair redirect rejected',502);let result:any;try{const text=await response.text();if(text.length>16384)throw new Error();result=JSON.parse(text);}catch{throw new ClientError('RESPONSE_INVALID','Invalid pairing response',502);}if(!response.ok)throw new ClientError('PAIR_REJECTED','Pair expired, consumed, denied or rate limited; start a new pair',response.status);return result.data as unknown;}
export async function startPair(options:{endpoint:string;name:string;configPath?:string}){const endpoint=cloudEndpoint(options.endpoint),path=await trustedPath(options.configPath),name=z.string().trim().min(1).max(100).parse(options.name);const health=await new ApiClient({mode:'cloud',endpoint,token:'health-probe'}).health();if(health.mode!=='cloud')throw new ClientError('ENVIRONMENT_MISMATCH','Pairing requires a cloud environment');const response=z.strictObject({device_code:z.string().min(1).max(512),user_code:z.string().min(1).max(100),expires_at:z.iso.datetime()}).parse(await pairRequest(endpoint,'start',{name}));const ttl=Date.parse(response.expires_at)-Date.now();if(ttl<=0||ttl>605000)throw new ClientError('RESPONSE_INVALID','Pair expiry exceeds ten minutes plus five seconds of clock tolerance');await privateJson(path+'.pair.json',{version:1,endpoint,name,device_code:response.device_code,expires_at:response.expires_at,environment_id:health.environment_id});return {user_code:response.user_code,expires_at:response.expires_at,endpoint,config_path:path,instruction:'Approve this user code in Graybox desktop, then run auth pair-complete. Retrieval is one-time; lost retrieval requires a new pair.'};}
export async function completePair(options:{configPath?:string;replace?:boolean}){const path=await trustedPath(options.configPath);let pending:z.infer<typeof pendingSchema>;try{pending=pendingSchema.parse(JSON.parse(await readFile(path+'.pair.json','utf8')));}catch{throw new ClientError('PAIR_MISSING','Start a pair first');}cloudEndpoint(pending.endpoint);if(Date.parse(pending.expires_at)<=Date.now())throw new ClientError('PAIR_EXPIRED','Start a new pair');let existing:Awaited<ReturnType<typeof readConfig>>|null=null;try{await readFile(path);existing=await readConfig(path);}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}if(existing?.config.environments.some(e=>e.environment_id===pending.environment_id)&&!options.replace)throw new ClientError('CONFIG_EXISTS','Environment already mapped; explicit replace required');const raw=await pairRequest(pending.endpoint,'poll',{device_code:pending.device_code});if(z.strictObject({status:z.literal('pending')}).safeParse(raw).success)return {status:'pending'};const response=approvedSchema.parse(raw);await rm(path+'.pair.json',{force:true});if(response.environment_id!==pending.environment_id||Date.parse(response.expires_at)<=Date.now())throw new ClientError('ENVIRONMENT_MISMATCH','Approved pair environment or expiry is invalid');const api=new ApiClient({mode:'cloud',endpoint:pending.endpoint,token:response.token}),health=await api.health(),identity=await api.me();if(health.mode!=='cloud'||health.environment_id!==response.environment_id||identity.agent_id!==response.agent_id||identity.human_id!==response.human_id)throw new ClientError('AGENT_MISMATCH','Approved agent does not match server identity');if(!(await api.workspaces()).some(w=>w.id===response.workspace_id))throw new ClientError('WORKSPACE_MISMATCH','Paired workspace is inaccessible');const credentials_file=join(dirname(path),'agent-'+response.agent_id+'.json');await privateJson(credentials_file,cloudCredentialsSchema.parse({mode:'cloud-agent',environment_id:response.environment_id,workspace_id:response.workspace_id,expires_at:response.expires_at,agent:{id:response.agent_id,human_id:response.human_id,name:pending.name,token:response.token,project_ids:identity.project_ids}}));const environment={mode:'cloud',endpoint:pending.endpoint,environment_id:response.environment_id,agent_id:response.agent_id,credentials_file};await privateJson(path,{version:1,environments:[...(existing?.config.environments??[]).filter(e=>e.environment_id!==response.environment_id),environment]});return {status:'approved',environment_id:response.environment_id,workspace_id:response.workspace_id,agent:identity,config_path:path};}
export async function pair(options:{endpoint:string;name:string;configPath?:string;replace?:boolean;signal?:AbortSignal;onStart?:(result:Awaited<ReturnType<typeof startPair>>)=>void}){const started=await startPair(options);options.onStart?.(started);while(Date.now()<Date.parse(started.expires_at)){options.signal?.throwIfAborted();const result=await completePair(options);if(result.status==='approved')return result;await new Promise<void>((resolve,reject)=>{const signal=options.signal;const abort=()=>{clearTimeout(timer);reject(new ClientError('PAIR_INTERRUPTED','Pairing interrupted; resume with auth pair-complete'));};const timer=setTimeout(()=>{signal?.removeEventListener('abort',abort);resolve();},3000);signal?.addEventListener('abort',abort,{once:true});});}throw new ClientError('PAIR_EXPIRED','Pair expired; start a new pair');}
