// Isolated local cloud-mode validation. Never connects to the production server.
import {config} from 'dotenv';
import {Pool} from 'pg';
import {randomBytes} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {migrate} from '../packages/db/src/migrate.ts';
import {bootstrapCloud} from './cloud-bootstrap.ts';
import {buildApp} from '../apps/api/src/app.ts';
config({quiet:true});
const base=new URL(process.env.GRAYBOX_TEST_ADMIN_URL!);
if(!['127.0.0.1','localhost'].includes(base.hostname)||base.port!=='55439'||base.pathname!=='/graybox_test')throw Error('Local isolated cluster required');
const control=new Pool({connectionString:base.href});
const database='graybox_cloud_validation';
const authPassword=randomBytes(32).toString('hex');
if((await control.query("SELECT 1 FROM pg_database WHERE datname=$1",[database])).rowCount)throw Error('Validation DB already exists; inspect it instead of overwriting');
if((await control.query("SELECT 1 FROM pg_roles WHERE rolname='graybox_auth'")).rowCount)throw Error('Auth role already exists; preserve its credential');
await control.query(`CREATE ROLE graybox_auth LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT PASSWORD '${authPassword}'`);
await control.query(`CREATE DATABASE ${database}`);
await control.end();
base.pathname='/'+database;
const admin=new Pool({connectionString:base.href});
await migrate(admin);
const runtimeUrl=new URL(process.env.GRAYBOX_TEST_DATABASE_URL!);runtimeUrl.pathname='/'+database;
const authUrl=new URL(base);authUrl.username='graybox_auth';authUrl.password=authPassword;
await admin.query(`REVOKE CONNECT ON DATABASE ${database} FROM PUBLIC; GRANT CONNECT ON DATABASE ${database} TO graybox_runtime,graybox_auth`);
const runtime=new Pool({connectionString:runtimeUrl.href}),auth=new Pool({connectionString:authUrl.href});
const app=await buildApp({pool:runtime,authPool:auth,mode:'cloud'});
const invitation=await bootstrapCloud(admin);
const password=randomBytes(24).toString('base64url');
const redeemed=await app.inject({method:'POST',url:'/v1/auth/redeem',payload:{code:invitation.code,username:'validation_owner',password,name:'云端验收账号'}});
if(redeemed.statusCode!==200)throw Error(`Restricted auth failed: ${redeemed.body}`);
const login=redeemed.json().data;
const projects=await app.inject({method:'GET',url:'/v1/projects',headers:{authorization:`Bearer ${login.token}`}});
if(projects.statusCode!==200)throw Error('Restricted runtime read failed');
await mkdir('.local',{recursive:true});
await writeFile('.local/cloud-validation.env',`GRAYBOX_MODE=cloud\nGRAYBOX_PORT=4328\nGRAYBOX_DATABASE_URL=${runtimeUrl.href}\nGRAYBOX_AUTH_DATABASE_URL=${authUrl.href}\n`,{mode:0o600});
await writeFile('.local/cloud-validation-user.json',JSON.stringify({username:'validation_owner',password,environment_id:login.environment_id,workspace_id:login.workspace_id}),{mode:0o600});
await app.close();await runtime.end();await auth.end();await admin.end();
console.log('Dedicated validation database and restricted-role login/read PASS. Secrets stored only in ignored .local files.');
