import {afterEach,expect,test,vi} from 'vitest';
import {ApiClient,cloudEndpoint} from '../../packages/client/src/client.ts';
import {startPair,completePair} from '../../packages/local-context/src/pairing.ts';
import {randomUUID} from 'node:crypto';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const dirs:string[]=[];afterEach(async()=>{vi.unstubAllGlobals();for(const d of dirs.splice(0))await rm(d,{recursive:true,force:true});});
test.each([700,6000])('pairing expiry clock skew %i ms remains bounded',async(skew)=>{
 const dir=await mkdtemp(join(tmpdir(),'graybox-pair-clock-'));dirs.push(dir);
 const environment_id=randomUUID(),expires_at=new Date(Date.now()+600000+skew).toISOString();
 vi.stubGlobal('fetch',async(url:string)=>new Response(JSON.stringify({data:url.endsWith('/start')?{device_code:'private-device',user_code:'TEST-CODE',expires_at}:{mode:'cloud',environment_id}}),{status:200}));
 const operation=startPair({endpoint:'https://graybox.example',name:'Clock test',configPath:join(dir,'client.json')});
 if(skew<5000)expect((await operation).user_code).toBe('TEST-CODE');else await expect(operation).rejects.toMatchObject({code:'RESPONSE_INVALID'});
});
test('cloud origins require HTTPS and reject URL credentials/path/query',()=>{expect(cloudEndpoint('https://graybox.example')).toBe('https://graybox.example');for(const endpoint of ['http://graybox.example','https://u:p@graybox.example','https://graybox.example/v1','https://graybox.example/?token=x'])expect(()=>cloudEndpoint(endpoint)).toThrow();expect(()=>new ApiClient({endpoint:'https://graybox.example',token:'secret'})).toThrow();});
test('pairing consumes agent response, validates identity and persists private config without printing token',async()=>{const dir=await mkdtemp(join(tmpdir(),'graybox-pair-'));dirs.push(dir);const ids={environment_id:randomUUID(),workspace_id:randomUUID(),agent_id:randomUUID(),human_id:randomUUID()},expires_at=new Date(Date.now()+60000).toISOString();const calls:Array<{path:string;auth:string|null}>=[];vi.stubGlobal('fetch',async(url:string,opts:RequestInit)=>{const path=new URL(url).pathname;calls.push({path,auth:new Headers(opts.headers).get('authorization')});const data=path.endsWith('/start')?{device_code:'device-secret',user_code:'ABCD-EFGH',expires_at}:path.endsWith('/poll')?{status:'approved',token:'agent-secret',expires_at,...ids}:path.endsWith('/health')?{mode:'cloud',environment_id:ids.environment_id}:path.endsWith('/me')?{credential_id:randomUUID(),kind:'agent',project_ids:null,agent_id:ids.agent_id,human_id:ids.human_id}:[{id:ids.workspace_id,name:'Team'}];return new Response(JSON.stringify({data}),{status:200});});const configPath=join(dir,'client.json');const started=await startPair({endpoint:'https://graybox.example',name:'CLI',configPath});expect(JSON.stringify(started)).not.toContain('device-secret');expect(started.user_code).toBe('ABCD-EFGH');const result=await completePair({configPath});expect(JSON.stringify(result)).not.toContain('agent-secret');expect(calls.filter(c=>c.path.includes('/auth/pair')).every(c=>c.auth===null)).toBe(true);const config=JSON.parse(await readFile(configPath,'utf8'));expect(config.environments[0]).toMatchObject({mode:'cloud',...{environment_id:ids.environment_id,agent_id:ids.agent_id}});});
test('cloud agent redirects never forward credentials',async()=>{const fetch=vi.fn(async(_url:string,_options:RequestInit)=>new Response('',{status:302,headers:{location:'https://evil.example'}}));vi.stubGlobal('fetch',fetch);const api=new ApiClient({mode:'cloud',endpoint:'https://graybox.example',token:'agent-secret'});await expect(api.me()).rejects.toMatchObject({code:'REDIRECT_REJECTED'});expect(fetch).toHaveBeenCalledTimes(1);expect(fetch.mock.calls[0]?.[1]).toMatchObject({redirect:'manual'});});
