import { afterEach, describe, expect, test } from 'vitest';
import { mkdtemp, mkdir, writeFile, rm, readFile,symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { createServer } from 'node:http';
import { ApiClient, ClientError, safeError } from '../../packages/client/src/client.ts';
import { resolveContext, bindProject, initializeConfig, defaultConfigPath,activateExperiment,createProject } from '../../packages/local-context/src/binding.ts';
import { gitMetadata } from '../../packages/local-context/src/git.ts';

const dirs:string[]=[];const servers:Array<ReturnType<typeof createServer>>=[];
afterEach(async()=>{for(const server of servers.splice(0))await new Promise<void>(r=>server.close(()=>r()));for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
async function setup() {
  const dir=await mkdtemp(join(tmpdir(),'graybox 中文 space '));dirs.push(dir);
  const human_id=randomUUID(),environment_id=randomUUID(),workspace_id=randomUUID(),project_id=randomUUID(),agent_id=randomUUID(),experiment_id=randomUUID();
  const calls:Array<{url:string;authorization?:string}>=[];const state={environment_id,workspace_id,project_id,agent_id,experiment_id,experiment_project:project_id};
  const server=createServer((req,res)=>{calls.push({url:req.url!,authorization:req.headers.authorization});res.setHeader('content-type','application/json');let data:unknown;
    if(req.url==='/v1/health')data={environment_id:state.environment_id,mode:'local'};
    else if(req.url==='/v1/me')data={credential_id:randomUUID(),human_id,agent_id:state.agent_id,kind:'agent',project_ids:null};
    else if(req.url===`/v1/projects/${project_id}`)data={id:project_id,workspace_id:state.workspace_id,revision:1};
    else if(req.url===`/v1/experiments/${experiment_id}`)data={id:experiment_id,project_id:state.experiment_project,revision:1};
    else {res.statusCode=404;res.end(JSON.stringify({error:{code:'NOT_FOUND',message:'Not found'}}));return;}res.end(JSON.stringify({data}));
  });servers.push(server);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const endpoint=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
  const credentials_file=join(dir,'credentials.json'),configPath=join(dir,'client.json'),repo=join(dir,'repo');await mkdir(repo);execFileSync('git',['init','-q'],{cwd:repo});
  await writeFile(credentials_file,JSON.stringify({mode:'local-demonstration-only',workspace_id,humans:[{id:randomUUID(),name:'Human',role:'owner',token:'human-secret'}],agents:[{id:agent_id,human_id,name:'Agent',token:'agent-secret',project_ids:null}]}));
  await writeFile(configPath,JSON.stringify({version:1,environments:[{environment_id,endpoint,credentials_file,agent_id}]}));
  const binding={version:1 as const,environment_id,workspace_id,project_id};await mkdir(join(repo,'.graybox'));await writeFile(join(repo,'.graybox','project.json'),JSON.stringify(binding));
  return {dir,repo,configPath,credentials_file,binding,endpoint,state,calls,agent_id,experiment_id};
}
describe('local context authority and discovery',()=>{
  test('resolves real Chinese/space nested cwd and safe agent identity without active experiment',async()=>{const f=await setup(),cwd=join(f.repo,'中文 nested');await mkdir(cwd);const ctx=await resolveContext({cwd,configPath:f.configPath});expect(ctx.binding).toEqual(f.binding);expect(ctx.paths.project_root).toBe(f.repo);expect(ctx.active_experiment).toBeNull();expect(JSON.stringify(ctx.safe)).not.toContain('agent-secret');});
  test('requires explicit absolute cwd',async()=>{await expect(resolveContext({cwd:'relative'})).rejects.toMatchObject({code:'CWD_REQUIRED'});});
  test('rejects wrong persistent environment before private read',async()=>{const f=await setup();f.state.environment_id=randomUUID();await expect(resolveContext({cwd:f.repo,configPath:f.configPath})).rejects.toMatchObject({code:'ENVIRONMENT_MISMATCH'});expect(f.calls).toHaveLength(1);});
  test('rejects unrelated project workspace',async()=>{const f=await setup();f.state.workspace_id=randomUUID();await expect(resolveContext({cwd:f.repo,configPath:f.configPath})).rejects.toMatchObject({code:'WORKSPACE_MISMATCH'});});
  test('rejects stale active experiment from another project',async()=>{const f=await setup();await writeFile(join(f.repo,'.graybox/local.json'),JSON.stringify({version:1,active_experiment_id:f.experiment_id}));f.state.experiment_project=randomUUID();await expect(resolveContext({cwd:f.repo,configPath:f.configPath})).rejects.toMatchObject({code:'EXPERIMENT_MISMATCH'});});
  test('rejects malicious endpoint/token repository fields',async()=>{const f=await setup();await writeFile(join(f.repo,'.graybox/project.json'),JSON.stringify({...f.binding,endpoint:'http://evil.example',token:'secret'}));await expect(resolveContext({cwd:f.repo,configPath:f.configPath})).rejects.toMatchObject({code:'BINDING_INVALID'});expect(f.calls).toHaveLength(0);});
  test('conflicting nested bindings fail instead of selecting project',async()=>{const f=await setup(),nested=join(f.repo,'nested');await mkdir(join(nested,'.graybox'),{recursive:true});await writeFile(join(nested,'.graybox/project.json'),JSON.stringify({...f.binding,project_id:randomUUID()}));await expect(resolveContext({cwd:nested,configPath:f.configPath})).rejects.toMatchObject({code:'BINDING_AMBIGUOUS'});});
  test('worktree has separate binding and ignores main checkout ancestors',async()=>{const f=await setup();execFileSync('git',['-c','user.name=Test','-c','user.email=test@example.invalid','commit','--allow-empty','-m','init'],{cwd:f.repo});const worktree=join(f.dir,'分支 worktree');execFileSync('git',['worktree','add','--detach',worktree,'HEAD'],{cwd:f.repo,stdio:'ignore'});await mkdir(join(worktree,'.graybox'));await writeFile(join(worktree,'.graybox/project.json'),JSON.stringify(f.binding));const ctx=await resolveContext({cwd:worktree,configPath:f.configPath});expect(ctx.paths.project_root).toBe(worktree);});
  test('different binding needs explicit replace and preserves local/unrelated files',async()=>{const f=await setup();const other={...f.binding,project_id:randomUUID()};await writeFile(join(f.repo,'.graybox/project.json'),JSON.stringify(other));await expect(bindProject({cwd:f.repo,configPath:f.configPath,binding:f.binding})).rejects.toMatchObject({code:'BINDING_EXISTS'});await bindProject({cwd:f.repo,configPath:f.configPath,binding:f.binding,replace:true});expect(JSON.parse(await readFile(join(f.repo,'.graybox/project.json'),'utf8'))).toEqual(f.binding);expect(await readFile(join(f.repo,'.git/info/exclude'),'utf8')).toContain('.graybox/local.json');});
  test('duplicate trusted environments are ambiguous',async()=>{const f=await setup();const config=JSON.parse(await readFile(f.configPath,'utf8'));config.environments.push(config.environments[0]);await writeFile(f.configPath,JSON.stringify(config));await expect(resolveContext({cwd:f.repo,configPath:f.configPath})).rejects.toMatchObject({code:'CONFIG_AMBIGUOUS'});});
  test('auth init selects a seeded agent and exposes no token',async()=>{const f=await setup();const configPath=join(f.dir,'new-client.json');const result=await initializeConfig({configPath,credentials_file:f.credentials_file,endpoint:f.endpoint,agent_id:f.agent_id});expect(result.environment_id).toBe(f.binding.environment_id);expect(JSON.stringify(result)).not.toContain('secret');expect(JSON.parse(await readFile(configPath,'utf8')).environments[0].agent_id).toBe(f.agent_id);});
  test('default trusted config is installation anchored',()=>{expect(defaultConfigPath).toMatch(/[\\/]graybox[\\/]\.local[\\/]client\.json$/);});
  test('clear can recover stale active context without skipping project identity checks',async()=>{const f=await setup();await writeFile(join(f.repo,'.graybox/local.json'),JSON.stringify({version:1,active_experiment_id:f.experiment_id}));f.state.experiment_project=randomUUID();await activateExperiment({cwd:f.repo,configPath:f.configPath,experiment_id:null});expect((await resolveContext({cwd:f.repo,configPath:f.configPath})).active_experiment).toBeNull();});
  test('explicit environment create cannot bypass stale bound experiment checks',async()=>{const f=await setup();await writeFile(join(f.repo,'.graybox/local.json'),JSON.stringify({version:1,active_experiment_id:f.experiment_id}));f.state.experiment_project=randomUUID();await expect(createProject({cwd:f.repo,configPath:f.configPath,environment_id:f.binding.environment_id},{type:'project_create',idempotency_key:randomUUID(),batch_id:randomUUID(),payload:{workspace_id:f.binding.workspace_id,name:'Blocked'}})).rejects.toMatchObject({code:'EXPERIMENT_MISMATCH'});});
  test('unbound create still requires existing explicit cwd',async()=>{const f=await setup();await expect(createProject({cwd:join(f.dir,'does-not-exist'),configPath:f.configPath,environment_id:f.binding.environment_id},{type:'project_create',idempotency_key:randomUUID(),batch_id:randomUUID(),payload:{workspace_id:f.binding.workspace_id,name:'Blocked'}})).rejects.toMatchObject({code:'CWD_INVALID'});});
  test('human credential identity is rejected even if trusted file claims agent token',async()=>{const f=await setup(),api=new ApiClient({endpoint:f.endpoint,token:'human-secret'});f.state.agent_id=null!;await expect(api.me()).rejects.toMatchObject({code:'AGENT_REQUIRED'});});
  test('auth init will not overwrite an environment without explicit replace',async()=>{const f=await setup();await expect(initializeConfig({configPath:f.configPath,credentials_file:f.credentials_file,endpoint:f.endpoint,agent_id:f.agent_id})).rejects.toMatchObject({code:'CONFIG_EXISTS'});});
  test('binding refuses a repository junction redirecting writes outside explicit cwd',async()=>{const f=await setup(),outside=join(f.dir,'outside');await mkdir(outside);await rm(join(f.repo,'.graybox'),{recursive:true,force:true});await symlink(outside,join(f.repo,'.graybox'),'junction');await expect(bindProject({cwd:f.repo,configPath:f.configPath,binding:f.binding})).rejects.toMatchObject({code:'CONTEXT_PATH_INVALID'});expect(await readFile(f.configPath,'utf8')).toContain('credentials_file');});
  test('optional Git metadata never invokes repository fsmonitor hooks or clean filters',async()=>{
    const f=await setup(),git=(args:string[])=>execFileSync('git',args,{cwd:f.repo,stdio:'pipe',windowsHide:true});await writeFile(join(f.repo,'tracked.txt'),'tracked\n');await writeFile(join(f.repo,'.gitattributes'),'*.txt filter=probe\n');git(['add','tracked.txt','.gitattributes']);
    await writeFile(join(f.repo,'.git/hooks/fsmonitor-probe'),'#!/bin/sh\nprintf observed > fsmonitor-was-run\nprintf "token\\000"\n');git(['config','core.fsmonitor','.git/hooks/fsmonitor-probe']);git(['config','filter.probe.clean','printf observed > filter-was-run; cat']);await writeFile(join(f.repo,'tracked.txt'),'changed\n');
    const metadata=await gitMetadata(f.repo);expect(metadata?.root).toBe(f.repo);await expect(readFile(join(f.repo,'fsmonitor-was-run'),'utf8')).rejects.toMatchObject({code:'ENOENT'});await expect(readFile(join(f.repo,'filter-was-run'),'utf8')).rejects.toMatchObject({code:'ENOENT'});
  });
});
describe('local HTTP client boundaries',()=>{
  test.each(['https://example.com','http://localhost:4318','http://127.0.0.1.evil:4318','http://user:agent-secret@127.0.0.1:4318','broken agent-secret'])('rejects unsafe endpoint without leaking secret: %s',endpoint=>{try{new ApiClient({endpoint,token:'agent-secret'});expect.fail('Must reject');}catch(e){expect(e).toBeInstanceOf(ClientError);expect(JSON.stringify(safeError(e))).not.toContain('agent-secret');}});
  test('redirect never forwards agent token',async()=>{const f=await setup();const redirect=createServer((_req,res)=>{res.writeHead(307,{location:f.endpoint+'/v1/me'});res.end();});servers.push(redirect);await new Promise<void>(r=>redirect.listen(0,'127.0.0.1',r));const api=new ApiClient({endpoint:`http://127.0.0.1:${(redirect.address() as {port:number}).port}`,token:'agent-secret'});await expect(api.me()).rejects.toMatchObject({code:'REDIRECT_REJECTED'});expect(f.calls).toHaveLength(0);});
  test('contract rejects missing stable key locally',async()=>{const f=await setup(),api=new ApiClient({endpoint:f.endpoint,token:'agent-secret'});await expect(api.command({type:'project_create',payload:{workspace_id:f.binding.workspace_id,name:'P'},batch_id:randomUUID()})).rejects.toMatchObject({code:'VALIDATION'});expect(f.calls).toHaveLength(0);});
  test('health does not disclose the credential',async()=>{const f=await setup(),api=new ApiClient({endpoint:f.endpoint,token:'agent-secret'});await api.health();expect(f.calls[0]!.authorization).toBeUndefined();});
  test('server failure redacts bearer secret and performs no automatic replay',async()=>{let calls=0;const server=createServer((_req,res)=>{calls++;res.writeHead(503,{'content-type':'application/json'});res.end(JSON.stringify({error:{code:'FAILED',message:'agent-secret reflected'}}));});servers.push(server);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const api=new ApiClient({endpoint:`http://127.0.0.1:${(server.address() as {port:number}).port}`,token:'agent-secret'});try{await api.me();expect.fail('Must fail');}catch(error){expect(JSON.stringify(safeError(error))).not.toContain('agent-secret');expect(safeError(error).error.code).toBe('FAILED');}expect(calls).toBe(1);});
  test('explicit timeout reports sanitized connection failure',async()=>{const server=createServer((_req,res)=>setTimeout(()=>res.end('{}'),80));servers.push(server);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const api=new ApiClient({endpoint:`http://127.0.0.1:${(server.address() as {port:number}).port}`,token:'agent-secret',timeout_ms:10});await expect(api.me()).rejects.toMatchObject({code:'CONNECTION_FAILED'});});
});
