import { afterEach, expect, test } from 'vitest';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { SyncJournal } from '../../packages/local-context/src/sync.ts';
import { ClientError } from '../../packages/client/src/client.ts';
const dirs:string[]=[];
afterEach(async()=>{for(const dir of dirs.splice(0))await rm(dir,{recursive:true,force:true});});
async function setup(){const dir=await mkdtemp(join(tmpdir(),'graybox-sync-'));dirs.push(dir);const scope={environment_id:randomUUID(),workspace_id:randomUUID(),project_id:randomUUID(),human_id:randomUUID(),agent_id:randomUUID(),cwd:dir};const scoped={...scope,entity_type:'project' as const,entity_id:scope.project_id};const journal=new SyncJournal(join(dir,'client.json'),scoped);const command={type:'project_update' as const,idempotency_key:randomUUID(),batch_id:randomUUID(),expected_revision:1,payload:{id:scope.project_id,name:'Verified'}};return {dir,scope:scoped,journal,command,operation_id:randomUUID(),response:{id:scope.project_id,revision:2,name:'Verified'}};}
test('persists exact stable keys before first send, retries uncertain writes, advances only after read-back',async()=>{const f=await setup();await f.journal.prepare(f.operation_id,'chat:turn-12',f.command);const calls:unknown[]=[];await expect(f.journal.execute(f.operation_id,async body=>{calls.push(body);throw new Error('lost response');},async()=>f.response)).rejects.toThrow('lost response');expect((await f.journal.read()).checkpoint).toBeNull();const recovered=new SyncJournal(join(f.dir,'client.json'),f.scope);await recovered.execute(f.operation_id,async body=>{calls.push(body);return f.response;},async()=>f.response);expect(calls).toEqual([f.command,f.command]);expect((await recovered.read()).checkpoint).toBe('chat:turn-12');expect(await readFile(recovered.path,'utf8')).not.toContain('token');let replayed=false;await recovered.execute(f.operation_id,async()=>{replayed=true;return f.response;},async()=>f.response);expect(replayed).toBe(false);});
test('read-back mismatch and read failure preserve pending receipt and checkpoint',async()=>{const f=await setup();await f.journal.prepare(f.operation_id,'turn-2',f.command);await expect(f.journal.execute(f.operation_id,async()=>f.response,async()=>({...f.response,name:'Wrong'}))).rejects.toMatchObject({code:'SYNC_UNVERIFIED'});await expect(f.journal.execute(f.operation_id,async()=>f.response,async()=>{throw new Error('read failed');})).rejects.toThrow('read failed');const state=await f.journal.read();expect(state.checkpoint).toBeNull();expect(state.receipts[0].state).toBe('pending');await expect(f.journal.prepare(randomUUID(),'turn-3',{...f.command,idempotency_key:randomUUID()})).rejects.toMatchObject({code:'SYNC_PENDING'});});
test('intent cannot replace persisted operation and identity scopes stay separate',async()=>{const f=await setup();await f.journal.prepare(f.operation_id,'turn-2',f.command);await expect(f.journal.prepare(f.operation_id,'turn-2',{...f.command,payload:{...f.command.payload,name:'Changed'}})).rejects.toMatchObject({code:'SYNC_CONFLICT'});const other=new SyncJournal(join(f.dir,'client.json'),{...f.scope,agent_id:randomUUID()});expect(other.path).not.toBe(f.journal.path);expect((await other.read()).receipts).toEqual([]);});
test('concurrent writer cannot replace pending intent',async()=>{const f=await setup();await f.journal.prepare(f.operation_id,'turn-2',f.command);let release!:()=>void;const blocked=new Promise<void>(r=>{release=r;});let entered!:()=>void;const ready=new Promise<void>(r=>{entered=r;});const sending=f.journal.execute(f.operation_id,async()=>{entered();await blocked;return f.response;},async()=>f.response);await ready;await expect(f.journal.prepare(randomUUID(),'turn-3',f.command)).rejects.toMatchObject({code:'SYNC_BUSY'});release();await sending;});
test('definitive exact-replay rejection preserves history and permits corrected new intent without advancing checkpoint',async()=>{const f=await setup();await f.journal.prepare(f.operation_id,'turn-2',f.command);const rejected=await f.journal.execute(f.operation_id,async()=>{throw new ClientError('REVISION_CONFLICT','Stale revision',409);},async()=>f.response);expect(rejected.state).toBe('rejected');expect((await f.journal.read()).checkpoint).toBeNull();const next=randomUUID(),corrected={...f.command,idempotency_key:randomUUID(),batch_id:randomUUID(),expected_revision:2};await f.journal.prepare(next,'turn-3',corrected);await f.journal.execute(next,async()=>({...f.response,revision:3}),async()=>({...f.response,revision:3}));const state=await f.journal.read();expect(state.receipts.map(r=>r.state)).toEqual(['rejected','verified']);expect(state.checkpoint).toBe('turn-3');});
test('inaccessible receipt or transport failure remains pending and cannot authorize a replacement',async()=>{const f=await setup();await f.journal.prepare(f.operation_id,'turn-2',f.command);for(const error of [new ClientError('VALIDATION','Contract changed before receipt lookup',400),new ClientError('FORBIDDEN','Authority changed',403),new ClientError('CONNECTION_FAILED','Timed out',503)])await expect(f.journal.execute(f.operation_id,async()=>{throw error;},async()=>f.response)).rejects.toBe(error);expect((await f.journal.read()).receipts[0].state).toBe('pending');expect((await f.journal.read()).checkpoint).toBeNull();await expect(f.journal.prepare(randomUUID(),'turn-3',{...f.command,idempotency_key:randomUUID()})).rejects.toMatchObject({code:'SYNC_PENDING'});});
